name: integration-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Integration test
        id: integration_test
        # Put your action repo here
        uses: oinume/create-milestone-action@milestone
      - name: Check outputs
        run: |
          test "${{ steps.integration_test.outputs.number }}" != ""
